# Generated by Django 4.2.6 on 2023-10-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('contato', models.CharField(blank=True, max_length=15, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto1', models.CharField(max_length=100)),
                ('produto2', models.CharField(max_length=100)),
                ('valorBase', models.DecimalField(blank=True, decimal_places=2, default=1.7, max_digits=10)),
                ('valorTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('create', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['valorTotal'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_p1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_p2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('valorProdutos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('subTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('combustivel', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.produto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.produto'),
        ),
    ]
