# Generated by Django 4.2.6 on 2023-10-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_produto1_produto_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto1', models.CharField(max_length=100)),
                ('valorBase_P1', models.DecimalField(blank=True, decimal_places=2, default=1.7, max_digits=10)),
                ('valorTotal_P1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('valor_p1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_P1', models.DateField(auto_now_add=True)),
                ('notes_P1', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['valorTotal_P1'],
            },
        ),
        migrations.CreateModel(
            name='Produto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto2', models.CharField(max_length=100)),
                ('valorBase_P2', models.DecimalField(blank=True, decimal_places=2, default=1.7, max_digits=10)),
                ('valorTotal_P2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('valor_p2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('create_P2', models.DateField(auto_now_add=True)),
                ('notes_P2', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['valorTotal_P2'],
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='valor_p1',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='valor_p2',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='produto1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventario.produto1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='produto2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.produto2'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='produto1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.produto1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='produto2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.produto2'),
        ),
    ]
