# Generated by Django 4.2.6 on 2023-10-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_produto1_produto2_remove_cliente_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto1',
            name='valorBase_P1',
        ),
        migrations.RemoveField(
            model_name='produto2',
            name='valorBase_P2',
        ),
        migrations.AddField(
            model_name='inventario',
            name='valorBase',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.7, max_digits=10),
        ),
    ]
