# Generated by Django 4.2.6 on 2023-10-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_produto1_valorbase_p1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('valorBase', models.DecimalField(blank=True, decimal_places=2, default=1.7, max_digits=10)),
                ('valorTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('create', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['valorTotal'],
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='produto1',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='produto2',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='produto1',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='produto2',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='valorBase',
        ),
        migrations.AddField(
            model_name='inventario',
            name='valor_p1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='valor_p2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Produto1',
        ),
        migrations.DeleteModel(
            name='Produto2',
        ),
        migrations.AddField(
            model_name='cliente',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.produto'),
            preserve_default=False,
        ),
    ]
