# Generated by Django 4.2.6 on 2023-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_produto_remove_cliente_produto1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='produto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
