# Generated by Django 4.2.6 on 2023-10-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_cliente_produto_cliente_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['cliente']},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['valorProdutos']},
        ),
    ]
