# Generated by Django 4.2.6 on 2023-10-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_cliente_options_alter_inventario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-valorProdutos']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-valorTotal']},
        ),
    ]
