# Generated by Django 4.2.6 on 2023-11-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_cliente_user_inventario_user_produto_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='user',
        ),
    ]
