# Generated by Django 4.2.6 on 2023-11-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_inventario_user_produto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.produto'),
            preserve_default=False,
        ),
    ]
